services:

  websitesa-helpers-yii2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: websitesa-helpers-yii2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - /var/.envs/.env:/var/.envs/.env
    env_file:
      - /var/.envs/.env
    restart: unless-stopped
    cpus: 0.3
    mem_limit: 512m
