services:

  yii2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: websitesa-helpers-yii2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    restart: unless-stopped
    cpus: 0.3
    mem_limit: 512m
